a_chat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'chat'

urlpatterns = [
    path('join/<str:room_name>/', views.chat_home, name='chat_home'),
    path('list/', views.chat_list, name='chat_list'),
    # HTMX routes
    path('chatroom/<str:room_name>/', views.open_chatroom, name='open_chatroom'),
    path('online_count/<str:room_name>/', views.online_count, name='online_count'),
    # Redirect Routes
    path('delete/<str:room_name>/', views.delete_chatroom, name='delete_chatroom'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

a_core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('a_home.urls')),
    path('chat/', include('a_chat.urls')),
    path("accounts/", include("allauth.urls")),
    path('users/', include("a_users.urls")),
    path('game/', include('a_game.urls')),
]

a_game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.game_home, name='home'),
    path('play/<str:game_name>/', views.play_game, name='play'),
    # htmx routes
    path('update_state/<str:game_name>/', views.update_game_state_view, name='update_state'),
    path('list/<str:started>/', views.game_list, name='list'),
]

a_game/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Game Types
BASIC = 'basic'
ADVANCED = 'advanced'

# Game States
IN_QUEUE = 'in_queue'
MORNING = 'morning'
DAY = 'day'
NIGHT = 'night'
VOTING = 'voting'
class Game(models.Model):
    GAME_TYPE_CHOICES = [
        (BASIC, 'Basic'),
        (ADVANCED, 'Advanced'),
    ]
    GAME_STATE_CHOICES = [
        (IN_QUEUE, 'In Queue'),
        (MORNING, 'Morning'),
        (DAY, 'Day'),
        (NIGHT, 'Night'),
        (VOTING, 'Voting'),
    ]
    type = models.CharField(
        max_length=20,
        choices=GAME_TYPE_CHOICES,
        default=BASIC
    )
    name = models.CharField(max_length=128, unique=True)
    player_group = models.ForeignKey(
        'a_game.PlayerGroup',
        on_delete=models.CASCADE,
        related_name='players'
    )
    state = models.CharField(
        max_length=20,
        choices=GAME_STATE_CHOICES,
        default=IN_QUEUE
    )
    
    chat_room = models.ForeignKey(
        'a_chat.ChatRoom',
        on_delete=models.CASCADE,
        related_name='game'
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
        
    class Meta:
        ordering = ['-created_at']

# Roles
INVESTIGATOR = 'investigator'
MURDERER = 'murderer'

class GamePlayer(models.Model):
    ROLE_CHOICES = [
        (INVESTIGATOR, 'Investigator'),
        (MURDERER, 'Murderer'),
    ]
    # parent models
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='game_players'
    )
    # game player attributes
    name = models.CharField(max_length=128)
    role = models.CharField(
        max_length=20,
        choices=ROLE_CHOICES,
        default=INVESTIGATOR
    )
    alive = models.BooleanField(default=True)
    
    def __str__(self):
        return f'{self.name} the {self.role}'
        
        
class PlayerGroup(models.Model):
    player_1 = models.ForeignKey(
        GamePlayer,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='player_1'
    )
    player_2 = models.ForeignKey(
        GamePlayer,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='player_2'
    )
    player_3 = models.ForeignKey(
        GamePlayer,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='player_3'
    )
    player_4 = models.ForeignKey(
        GamePlayer,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='player_4'
    )

a_game/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Game
from django.forms import ModelForm


class GameCreateForm(ModelForm):
    class Meta:
        model = Game
        fields = ['type']
        labels = {
            'type': 'Game Type',
        }
        widgets = {
            'type': forms.Select(choices=Game.GAME_TYPE_CHOICES),
        }

a_game/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotAllowed, HttpRequest, HttpResponse

from .models import Game
from .forms import GameCreateForm
from .logic import create_game, update_game_state



# Create your views here.
def game_home(request: HttpRequest):
    template = 'a_game/find_game.html'
    
    if request.method == 'POST':
        print(f"Form Post: {request.POST}")
        form = GameCreateForm(request.POST)
        if form.is_valid():
            post_data = form.cleaned_data
            game_type = post_data['type']
            new_game = create_game(request.user, game_type)
            
            if new_game:
                print(f"New Game: {new_game}")
                return redirect('game:play', game_name=new_game.name)
            else:
                print(f"Form Errors: {form.errors}")
                return redirect('game:home')
        else:
            print(f"Form Errors: {form.errors}")
    if not request.user.profile.is_guest:
        form = GameCreateForm()
    else:
        form = ""
    games = Game.objects.all().filter(state='in_queue')
    context = {
        'games': games,
        'form': form,
    }
    return render(request, template, context)

def game_list(request, started: str):
    print(f"Game List: {started}")
    template = 'a_game/partials/game_list.html'
    if started == 'false':
        games = Game.objects.all().filter(state='in_queue')
    else:
        # any game thats NOT in the queue
        games = Game.objects.all().filter(state__in=['morning', 'day', 'night', 'voting'])
    context = {
        'games': games,
        'started': started,
    }
    return render(request, template, context)
    
def play_game(request, game_name: str):
    template = 'a_game/play_game.html'
    game = Game.objects.get(name=game_name)
    chat_room = game.chat_room
    context = {
        'game': game,
        'chat_room': chat_room,
    }
    return render(request, template, context)

def update_game_state_view(request, game_name: str):
    if request.method == 'POST':
        try:
            # get the post data
            post_data = request.POST
            game = Game.objects.get(name=game_name)
            # validate the post data
            if 'state' not in post_data:
                raise Exception("Invalid post data: state not found")
            state = post_data['state']
            try:
                new_state = update_game_state(game, state)
                return render(request, 'a_game/partials/game_state.html', {
                    'game': game,
                    'state': new_state,
                    })
            except Exception as e:
                print(f"Error updating game state: {str(e)}")
            # any other logic or data needed to be updated
            # alive players, day_
        except Exception as e:
            print(f"Error updating game state: {str(e)}")
            return HttpResponseNotAllowed(['POST'])

a_game/templates/a_game/find_game.html
{% extends 'layouts/blank.html' %}

{% block content %}
<div class="sb-secondary sb-flex sb-flex-col sb-w-full sb-px-4">
  <h1 class="sb-text-center">Find Game</h1>
  
  <div class="sb-flex sb-flex-col sb-gap-4">
    <div 
    id="games-list"
    class="sb-flex sb-gap-4 sb-md:flex-wrap sb-flex-wrap sb-mb-n
    sb-md:flex-row sb-flex-col sb-mb-4"
    hx-get="{% url 'game:list' 'false' %}"
    hx-trigger="load"
    hx-swap="outerHTML"
    >
    </div>
    <div class="sb-border-t-4 sb-border-primary sb-w-full sb-mb-4"></div>
    {% if user.profile.is_guest %}
        <div class="sb-black sb-flex sb-items-center sb-justify-center sb-flex-col sb-w-full sb-gap-4">
            <div class="sb-bg-white sb-rounded-lg sb-p-6 sb-shadow-md sb-w-2/3">
                <h3 class="sb-text-xl sb-font-semibold sb-mb-4">Guest Mode</h3>
                <div class="sb-space-y-3">
                    <p>You are currently in guest mode.</p>
                    <p>To create a new game, please login.</p>
                </div>
            </div>
        </div>
    {% else %}
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button 
        type="submit"
        class="sb-w-full sb-mt-2 sb-p-2 sb-cursor-pointer sb-mb-6"
        >
            Create Game
        </button>
    </form>
    {% endif %}
</div>
{% endblock %}

a_game/templates/a_game/play_game.html
{% extends 'layouts/blank.html' %}

{% block content %}
<div class="sb-flex sb-flex-col sb-gap-4 sb-secondary game-holder">
  <a href="{% url 'game:home' %}">
    <button class="sb-text-center w-full sb-p-2 sb-cursor-pointer sb-mt-2">
    Back
    </button>
  </a>
    <h1>{{ game.name }}</h1>
    <h2>State: <span id="game-state">{{ game.state }}</span></h2>
    <span>{{ game.created_at }}</span>
    <p class="sb-text-center">{{game.type}}</p>
      {% if game.state == 'in_queue' %}
        <button 
        id="state-change-button"
        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
        hx-post="{% url 'game:update_state' game.name %}"
        hx-target="#game-state"
        hx-swap="innerHTML"
        hx-vals='{"state": "morning"}'
        class="sb-text-center w-full sb-p-2 sb-cursor-pointer sb-mb-6"
        >
            Start Game
        </button>
      {% else %}
      {% include 'a_game/partials/widgets/state_change_button.html' with state=game.state %}
      {% endif %}
</div>




<div class="sb-w-full chat-holder">
  <div class="sb-flex sb-items-center sb-justify-center sb-flex-col sb-w-full">
    <div class="sb-flex sb-w-full">
      <div 
      id="chat-room"
      hx-trigger="load"
      hx-get="/chat/chatroom/{{ chat_room.name }}/"
      ></div>
      <div
        id="online-count"
        hx-trigger="load"
        hx-get="/chat/online_count/{{ chat_room.name }}/"
        ></div>
    </div>
  </div>
</div>
{% endblock %}