a_chat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'chat'

urlpatterns = [
    path('join/<str:room_name>/', views.chat_home, name='chat_home'),
    path('list/', views.chat_list, name='chat_list'),
    # HTMX routes
    path('chatroom/<str:room_name>/', views.open_chatroom, name='open_chatroom'),
    path('online_count/<str:room_name>/', views.online_count, name='online_count'),
    # Redirect Routes
    path('delete/<str:room_name>/', views.delete_chatroom, name='delete_chatroom'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

a_core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('a_home.urls')),
    path('chat/', include('a_chat.urls')),
    path("accounts/", include("allauth.urls")),
    path('users/', include("a_users.urls")),
    path('game/', include('a_game.urls')),
]

a_users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/<str:username>/', views.profile_view, name='profile'),
]

a_chat/models.py
from django.db import models
from django.contrib.auth.models import User

class ChatRoom(models.Model):
    name = models.CharField(max_length=128, unique=True)
    users_joined = models.ManyToManyField(
        User,
        related_name='users_joined',
        blank=True
    )
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = f"Room {self.id}"
            
        self.name.replace(" ", "_")
        return super().save(*args, **kwargs)
    
class ChatMessage(models.Model):
    room = models.ForeignKey(
        ChatRoom,
        related_name="messages",
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    body= models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return f'{self.author.username}: {self.body}'
    
    class Meta:
        ordering = ['-created_at']

a_chat/forms.py
from django.forms import ModelForm
from django import forms

from .models import *

class ChatMessageCreateForm(ModelForm):
    class Meta:
        model = ChatMessage
        fields = ['body']
        labels = {
            'body': '',
        }
        widgets = {
            'body': forms.TextInput(
                attrs={
                    'placeholder': 'Add message ...', 
                    'class': 'sb-p-2 sb-black sb-w-full', 
                    'maxlength': '300', 
                    'autofocus': True}),
        }
        
class ChatRoomCreateForm(ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        return name.replace(' ', '_')
    
    class Meta:
        model = ChatRoom
        fields = ['name']
        labels = {'name': ''}
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'New Room Name', 
                    'class': 'sb-p-2 sb-black', 
                    'maxlength': '32', 
                    'autofocus': True}),
            
        }

a_chat/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .forms import ChatMessageCreateForm, ChatRoomCreateForm
from .models import ChatRoom

def chat_home(request, room_name):
    context = {
        'chat_room': ChatRoom.objects.get(name=room_name),
    }
    return render(request, 'home.html', context)

def chat_list(request):
    form = ChatRoomCreateForm()
    if request.method == 'POST':
        if request.user.profile.is_guest:
            return redirect('chat:chat_list')
        form = ChatRoomCreateForm(request.POST)
        if form.is_valid():
            chat_room = form.save()
            return redirect('chat:chat_home', room_name=chat_room.name)
    chat_rooms = ChatRoom.objects.all()
    context = {
        'chat_rooms': chat_rooms,
        'form': form
    }
    return render(request, 'a_chat/chat_list.html', context)

def open_chatroom(request, room_name):
    template = 'a_chat/chat_room.html'
    
    chat_room = get_object_or_404(ChatRoom, name=room_name)
    messages = chat_room.messages.all()[:30]
    print(f"Chat Room: {chat_room}")
    form = ChatMessageCreateForm()
    
    if request.method == 'POST':
        print(f"Form POST: {form.is_valid()}")
        form = ChatMessageCreateForm(request.POST)
        if form.is_valid():
            print(f"Form Valid: {form.is_valid()}")
            message = form.save(commit=False)
            message.author = request.user
            message.room = chat_room
            message.save()
            print(f"Message Saves: {message}")
            context = {
                'chat_message': message,
                'user': request.user,
            }
            return render(
                request, 'a_chat/partials/chat_message_p.html', context
                )
        else:
            print(f"Form Errors: {form.errors}")
    context = {
        'chat_room': chat_room,
        'chat_messages': messages,
        'form': form,
        'user': request.user,
    }
    return render(request, template, context)

def online_count(request, room_name):
    template = 'a_chat/partials/online_count.html'
    room = ChatRoom.objects.get(name=room_name)
    online_count = room.users_joined.count()
    context = {
        'online_count': online_count,
    }
    return render(request, template, context)

def delete_chatroom(request, room_name):
    chat_room = get_object_or_404(ChatRoom, name=room_name)
    chat_room.delete()
    return redirect('chat:chat_list')

a_chat/templates/a_chat/partials/chat_message_p.html
<div id="chat-messages" hx-swap-oob="beforeend">
    <div class="sb-animate-fade">
        {% include 'a_chat/chat_message.html' %}
    </div>

    <script>scrollToBottom()</script>

</div>

a_chat/templates/a_chat/partials/online_count.html
<div 
class="sb-flex sb-grow sb-flex-col sb-items-end sb-justify-center "
id="online-count"
hx-swap-oob="outerHTML"
>
    <div class="sb-w-1/2 sb-md:w-1/4 sb-h-32 sb-border-t-4 sb-border-b-8 sb-border-l sb-border-r
    sb-border-solid sb-border-primary sb-bg-white sb-p-2">
        <h3 class="sb-text-center">{{online_count}} Users Online</h3>
        <div 
        id="users-online-list"
        class="users-online-list">
            {% for user in chat_room.users_joined.all %}
            <div class="users-online-list-item">{{user.username}}
            </div>
            {% endfor %}
        </div>
    </div>
</div>

a_chat/templates/a_chat/partials/username_in_message.html
<div class="sb-flex sb-flex-col">
    <a class="username-link sb-flex sb-flex-col sb-items-start sb-cursor-pointer"
        href="{% url 'users:profile' chat_message.author.username %}"
    >
        {% if chat_message.author == user %}
            <span class="message-username own-message-username">
                {{ chat_message.author.username }}
            </span>
        {% else %}
            <span class="message-username">
                {{ chat_message.author.username }}
            </span>
        {% endif %}
    </a>
    <div class="sb-pb-1 sb-flex sb-grow message-time sb-secondary 
{% if chat_message.author == user %}
    sb-justify-end 
{% else %}
    sb-justify-start
{% endif %}
    sb-px-2 sb-items-end">
            <span class="chat-time"></span>
                {{ chat_message.created_at|date:"M d, H:i" }}
            </span>
    </div>
</div>